version: '3.9'

services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: blink-dotfiles:alpine
    environment:
      - SSH_USER=blink
      - SSH_PASSWORD=blnik
    user: ${SSH_USER}
    volumes:
      - .:/usr/src/blink-dotfiles
    ports:
      - 0.0.0.0:22022:22/tcp
      - 0.0.0.0:22022:22022/udp
