version: '3.9'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: blink-dotfiles:ubuntu
    environment:
      - SSH_USER=blink
      - SSH_PASSWORD=blnik
    user: ${SSH_USER}
    volumes:
      - .:/usr/src/blink-dotfiles
    ports:
      - 0.0.0.0:22022:22/tcp
      - 0.0.0.0:22022:22022/udp

