set nocompatible

let s:dein_plugin_dir = '~/.cache/vim/dein'
let s:dein_install_dir = s:dein_plugin_dir . '/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+=' . expand(s:dein_install_dir)

if has('vim_starting')
  if dein#load_state(s:dein_plugin_dir)
    let g:dein#auto_recache = 1
    let g:dein#install_max_processes = 12
    call dein#begin(s:dein_plugin_dir)
    call dein#add(s:dein_install_dir)
    if ! has('nvim')
      call dein#add('roxma/nvim-yarp', { 'depends': 'vim-hug-neovim-rpc' })
      call dein#add('roxma/vim-hug-neovim-rpc')
    endif
    call dein#add('Shougo/deoplete.nvim')

    """ With nvim we should use ojroques's repo, details:  https://github.com/fcpg/vim-osc52/issues/6
    call dein#add('ojroques/vim-oscyank')
    " call dein#add('fcpg/vim-osc52')

    call dein#end()
    call dein#save_state()
  endif
endif

filetype plugin indent on
syntax enable

if ! has('nvim')
  set t_Co=256
  " Set Vim-specific sequences for RGB colors
  " Fixes 'termguicolors' usage in vim+tmux
  " :h xterm-true-color
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" Enables 24-bit RGB color in the terminal
if has('termguicolors')
  if empty($COLORTERM) || $COLORTERM =~# 'truecolor\|24bit'
    set termguicolors
  endif
endif

" Use system clipboard to get buffers synced between TMUX and VIM
if has('clipboard') && has('vim_starting')
  " set clipboard& clipboard+=unnamedplus
  set clipboard& clipboard^=unnamed,unnamedplus
endif

if exists('##TextYankPost')
  augroup BlinkClipboardIntegration
    autocmd!
    autocmd TextYankPost * silent! if v:event.operator ==# 'y' | call YankOSC52(join(v:event["regcontents"],"\n")) | endif
  augroup END
endif
