# Always start tmux if it isn't yet.
if [ -z "$TMUX" ]
then
  tmux
fi

# History improvements 
export HISTFILE=~/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export SAVEHIST=100000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS

# PATH
export PATH=$PATH:$HOME/.bin

# ALIASES
alias k=kubectl

# TOOLS
kubectl () {
    command kubectl $*
    if [[ -z $KUBECTL_COMPLETE ]]
    then
        source <(command kubectl completion zsh)
        KUBECTL_COMPLETE=1 
    fi
}
source /usr/share/nvm/init-nvm.sh

# Starship
export STARSHIP_CONFIG=~/.starship.toml
eval "$(starship init zsh)"
